### ISSUE TITLE
Update CI workflow to remove the `if` that disables running on PRs

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Discord#64]
In https://github.com/cake-contrib/Cake.Recipe/issues/809 we established that the `if` in 

```yaml
# ...
build:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
# ...
```

does more harm than good, and should be replaced by limiting the branches which are build on `push`:

```yaml
push:
  branches:
    - main
    - develop
    - "feature/**"
    - "release/**"
    - "hotfix/**"
    - "support/**"
  tags:
    - "*"
```
